metadata.format.version = "1.1"

[versions]

paper = "1.21.8-R0.1-SNAPSHOT"

runtask = "3.0.2"

miniplaceholders = "3.1.0"
adventure = "4.26.1"

vault = "1.7.1"

[libraries]

paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }

[plugins]

runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
